-- Электронная система тестирования студентов: начальная схема БД

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    role          VARCHAR(20)  NOT NULL,
    group_name    VARCHAR(30),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'TEACHER', 'STUDENT'))
);

CREATE TABLE subjects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE tests (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(200) NOT NULL,
    description        VARCHAR(1000),
    subject_id         BIGINT       NOT NULL REFERENCES subjects (id),
    author_id          BIGINT       NOT NULL REFERENCES users (id),
    time_limit_minutes INTEGER      NOT NULL,
    passing_score      INTEGER      NOT NULL,
    published          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    CONSTRAINT chk_tests_time CHECK (time_limit_minutes BETWEEN 1 AND 300),
    CONSTRAINT chk_tests_passing CHECK (passing_score BETWEEN 0 AND 100)
);

CREATE TABLE questions (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id  BIGINT        NOT NULL REFERENCES tests (id) ON DELETE CASCADE,
    text     VARCHAR(1000) NOT NULL,
    type     VARCHAR(20)   NOT NULL,
    points   INTEGER       NOT NULL DEFAULT 1,
    position INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT chk_questions_type CHECK (type IN ('SINGLE', 'MULTIPLE')),
    CONSTRAINT chk_questions_points CHECK (points BETWEEN 1 AND 100)
);

CREATE TABLE answer_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT       NOT NULL REFERENCES questions (id) ON DELETE CASCADE,
    text        VARCHAR(500) NOT NULL,
    correct     BOOLEAN      NOT NULL DEFAULT FALSE,
    position    INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE test_attempts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id     BIGINT      NOT NULL REFERENCES tests (id) ON DELETE CASCADE,
    student_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status      VARCHAR(20) NOT NULL,
    started_at  TIMESTAMP   NOT NULL,
    finished_at TIMESTAMP,
    score       INTEGER     NOT NULL DEFAULT 0,
    max_score   INTEGER     NOT NULL DEFAULT 0,
    percent     INTEGER     NOT NULL DEFAULT 0,
    passed      BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_attempts_status CHECK (status IN ('IN_PROGRESS', 'FINISHED'))
);

CREATE TABLE attempt_answers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id    BIGINT  NOT NULL REFERENCES test_attempts (id) ON DELETE CASCADE,
    question_id   BIGINT  NOT NULL REFERENCES questions (id) ON DELETE CASCADE,
    correct       BOOLEAN NOT NULL DEFAULT FALSE,
    points_earned INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_attempt_question UNIQUE (attempt_id, question_id)
);

CREATE TABLE attempt_answer_options (
    attempt_answer_id BIGINT NOT NULL REFERENCES attempt_answers (id) ON DELETE CASCADE,
    option_id         BIGINT NOT NULL REFERENCES answer_options (id) ON DELETE CASCADE,
    PRIMARY KEY (attempt_answer_id, option_id)
);

CREATE INDEX idx_tests_subject ON tests (subject_id);
CREATE INDEX idx_tests_author ON tests (author_id);
CREATE INDEX idx_questions_test ON questions (test_id);
CREATE INDEX idx_options_question ON answer_options (question_id);
CREATE INDEX idx_attempts_test ON test_attempts (test_id);
CREATE INDEX idx_attempts_student ON test_attempts (student_id);
CREATE INDEX idx_answers_attempt ON attempt_answers (attempt_id);
